CREATE DATABASE IF NOT EXISTS dbs;

DROP TABLE IF EXISTS dbs.users;
CREATE TABLE dbs.users(
  id INT AUTO_INCREMENT PRIMARY KEY ,
  username VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL
);

  SELECT * FROM dbs.users;